version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        uid: ${UID}
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./apache_log:/var/log/apache2
    ports:
      - 8090:80
volumes:
  src: